### ISSUE TITLE
Make into a Pip Package

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/image-titler#4]
In the same way we turned the wiki generator into a package, let's try making this into a package. That'll make it much easier since we'll be able to pip the script from anywhere by name, and we can build a nice local script for it instead of the nasty shortcut we're using now:

```
pip install image-titler
image-titler -o /some/output/directory/
```

**Comment by hmajid2301** [comment]
I can look at this.

**Comment by jrg94** [comment]
That would be awesome! If you take a look at the wiki generator, I actually push a new version of it to pip via Travis CI every time we increment its version.
